name: audio
description: Music Test

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_name: "^0.0.1"

flutter_launcher_name:
  name: "Audio"

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  just_audio: ^0.7.5


flutter:
  uses-material-design: true

  assets:
    - assets/
#  fonts:
#    - family: JosefinSans
#      fonts:
#        - asset: fonts/JosefinSans.ttf
#    - family: FredokaOne
#      fonts:
#        - asset: fonts/FredokaOne-Regular.ttf
